### ISSUE TITLE
Slot names on HD races

### ISSUE THREAD

**Issue by yadreny** [kenamis/UMAHumanHD#1]
Thank you for this solution for HDRP.
Taking the opportunity to express the idea, perhaps it is better to avoid "HD" postfix in the naming of slots, to make them same as on HumanMale and HumanMaleDCS, otherwise, all recipes from assets have to add it to the hide base slot.

**Comment by yadreny** [comment]
And what about meshHideAssets?

**Comment by kenamis** [comment]
I added the postfix on purpose so that it couldn't be used with existing recipes because those recipes need to be recreated with a compatible uma material.  Do you think there is a better way?

What's your question about meshHideAssets?  Those are usually created from the equipment's viewpoint which this package contains none of.

**Comment by yadreny** [comment]
My goal is easy migration to HDRP, my project includes a decent amount of UMA content, and I think how to do it with minimal difficulties. Looks like I found a solution after my last message. I converted four basic UMA materials using "Edit>Render Pipeline>Upgrade Selected" and added Cross Compatibility between old slots and HD slots. If I remembered about compatibility feature earlier I wouldn't bother you. Probably my solution is not perfect but as far as I can see it works quite well with assets by Will Barry. Haven't checked but I think meshHideAssets should also work.
