### ISSUE TITLE
Imcompatibilty with Hair,cloth,etc from UMA 2

### ISSUE THREAD

**Issue by vazan** [kenamis/UMAHumanHD#2]
Hi,
Maybe it's totaly normal, your HUMAN HD, does'nt seem to be compatible with the clothing, hair,etc from UMA 2 or other package ? Did you know if something can be done to make it work ?

**Comment by kenamis** [comment]
If I understand your question correctly, it's because I purposely made HumanHD not a compatible race to force people to realize that all the existing clothing would need to be upgraded too.  When I originally made this, there wasn't a simple shader, material, and uma material upgrade from built-in to HDRP.

**Comment by vazan** [comment]
ok. however i'm pretty new with UMA , did you know how we need to proceed to update these parts ?

**Comment by kenamis** [comment]
Have you joined the discord channel? I would suggest asking for help there.  I don't support UMA anymore.
https://discord.gg/m6DkSPjWmr
